title: RISY Oussama
logo : Profile_picture.png
description : I’m a data professional with a strong foundation in analytics, visualization, and cloud platforms, combined with deep expertise in AI and machine learning for healthcare. My journey bridges business intelligence tools like Tableau, Power BI, and SQL with advanced deep learning projects in computer vision and medical imaging. Whether it’s building dashboards to uncover insights, developing segmentation models for renal tumors, or experimenting with AI-driven assistants for healthcare environments, I thrive at the intersection of data, AI, and real-world impact. 
show_downloads : true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
